-- Crear Base de datos
CREATE DATABASE phishguard; 

-- Conecciòn a la Base de datos;
\c phishguard;

-- Crear la tabla Usuarios
CREATE TABLE users (
    user_id SERIAL PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    registration_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    role VARCHAR(20) NOT NULL
);

-- Crear la tabla URLs
CREATE TABLE URLS (
	ID_URL SERIAL PRIMARY KEY,
	URL VARCHAR(500) NOT NULL,
	FECHA_VERIFICACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ESTADO VARCHAR(50) NOT NULL,
	RIESGO_PORCENTAJE FLOAT NOT NULL,
	ID_USUARIO INT REFERENCES USUARIOS (ID_USUARIO) ON DELETE CASCADE
);

-- Crear la tabla Análisis
CREATE TABLE ANALISIS (
	ID_ANALISIS SERIAL PRIMARY KEY,
	ID_URL INT REFERENCES URLS (ID_URL) ON DELETE CASCADE,
	RESULTADO_TRACEROUTE TEXT NOT NULL,
	METODOLOGIA VARCHAR(100) NOT NULL,
	RIESGO_PORCENTAJE FLOAT NOT NULL,
	FECHA_ANALISIS TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Crear la tabla Proveedores
CREATE TABLE PROVEEDORES (
	ID_PROVEEDOR SERIAL PRIMARY KEY,
	NOMBRE_PROVEEDOR VARCHAR(100) NOT NULL,
	CORREO_PROVEEDOR VARCHAR(100) NOT NULL,
	ID_URL INT REFERENCES URLS (ID_URL) ON DELETE CASCADE
);